#!/bin/sh -e                                                        
                  
start() {                                                
        echo "mdev: starting"
		echo /sbin/mdev > /proc/sys/kernel/hotplug
}                                   
                                    
stop() {                            
        echo "mali: stopping"
		echo "" > /proc/sys/kernel/hotplug
                  
}            
             
case "$1" in 
start)       
        start
;;          
stop)       
        stop                                            
;;            
restart)     
        stop                              
        start                                                       
;;                                                                  
*)                                                                  
        echo "mali: Please use start, stop, or restart."
        exit 1                       
;;                                   
esac 
